<?php
// deploy

#   TITLE   : Gitub Production Server Deployer Service   
#   DESC    : Automatically update the scripts for the servers. This will be the Push to Repository script 
#   PROPRIETOR: VARSITYMARKET_TECHNOLOGIES
#   VERSION : 1.0.1.1
#   AUTHOR  : HARDY HASTINGS  
#   RELEASE : 2025/09/16

$intro_text = " 
##############################################

    -- Developer Console --
    -- Configure the varsitymarket ecosystem. With this command line tool 

##############################################
\t__     ___    ____  ____ ___ _______   __
\t\ \   / / \  |  _ \/ ___|_ _|_   _\ \ / /
\t \ \ / / _ \ | |_) \___ \| |  | |  \ V /
\t  \ V / ___ \|  _ < ___) | |  | |   | |
\t   \_/_/   \_\_| \_\____/___| |_|   |_|
\t
\t __  __    _    ____  _  _______ _____
\t|  \/  |  / \  |  _ \| |/ / ____|_   _|
\t| |\/| | / _ \ | |_) | ' /|  _|   | |
\t| |  | |/ ___ \|  _ <| . \| |___  | |
\t|_|  |_/_/   \_\_| \_\_|\_\_____| |_|
\t
\t _            _                 _             _
\t| |_ ___  ___| |__  _ __   ___ | | ___   __ _(_) ___  ___
\t| __/ _ \/ __| '_ \| '_ \ / _ \| |/ _ \ / _` | |/ _ \ / __|
\t| ||  __/ (__| | | | | | | (_) | | (_) | (_| | |  __/\__ \
\t \__\___|\___|_| |_|_| |_|\___/|_|\___/ \__, |_|\___||___/
\t                                        |___/
\t[SYNC-SERVICES] => Gitub Deploying Application
\tCreated By Hardy Hastings                                        
\tThis application is responsible for managing code from production to development. 
\n\n
";

echo($intro_text);
sleep(5); 

// Start the CLI interaction loop
while (true) {
    echo "\nDescribe The Changes You Have Made: ";
    // Read user input from the console
    $line = trim(fgets(STDIN));
    // Split the input into command and arguments
    $parts = explode(' ', $line, 2); // Split only on the first space to get command and rest of the line
    $description = $line;
    $args = $parts[1] ?? ''; // Get the rest of the line as arguments    

    // Set the directory you want to serve
    $cur_dir = dirname(dirname(dirname(__FILE__))).DIRECTORY_SEPARATOR; 
    // Change to the specified directory
    chdir($cur_dir);

    #$command = 'git init'; 
    // Open a log file to capture the output
    // Start the server process and redirect output to the log file
    #$process = popen($command, 'r');

    #if (is_resource($process)) {
    #}

    $command = 'git add .'; 
    // Open a log file to capture the output
    // Start the server process and redirect output to the log file
    $process = popen($command, 'r');

    if (is_resource($process)) {
    }

    
    $command = 'git commit -m "'.$line.'"'; 

    // Open a log file to capture the output
    // Start the server process and redirect output to the log file
    $process = popen($command, 'r');

    if (is_resource($process)) {
    }



    $command = '# git push origin main '; 
    // Open a log file to capture the output
    // Start the server process and redirect output to the log file
    $process = popen($command, 'r');

    if (is_resource($process)) {
    }



    exit(0);
}
?>