<?php
// local.serever.script

#   TITLE   : LOCAL PHP WEB SERVER   
#   DESC    : The local server will be used to run the control panel. This will run on port 3000. To prevent local ports crashing with development ports, the application ports will m be different. 
#   PROPRIETOR: VARSITYMARKET_TECHNOLOGIES
#   VERSION : 1.0.1.2
#   AUTHOR  : HARDY HASTINGS  
#   RELEASE : 2025/10/23

$intro_text = " 
##############################################

    -- Developer Console --
    -- Configure the varsitymarket ecosystem. With this command line tool 

##############################################
\t__     ___    ____  ____ ___ _______   __
\t\ \   / / \  |  _ \/ ___|_ _|_   _\ \ / /
\t \ \ / / _ \ | |_) \___ \| |  | |  \ V /
\t  \ V / ___ \|  _ < ___) | |  | |   | |
\t   \_/_/   \_\_| \_\____/___| |_|   |_|
\t
\t __  __    _    ____  _  _______ _____
\t|  \/  |  / \  |  _ \| |/ / ____|_   _|
\t| |\/| | / _ \ | |_) | ' /|  _|   | |
\t| |  | |/ ___ \|  _ <| . \| |___  | |
\t|_|  |_/_/   \_\_| \_\_|\_\_____| |_|
\t
\t _            _                 _             _
\t| |_ ___  ___| |__  _ __   ___ | | ___   __ _(_) ___  ___
\t| __/ _ \/ __| '_ \| '_ \ / _ \| |/ _ \ / _` | |/ _ \ / __|
\t| ||  __/ (__| | | | | | | (_) | | (_) | (_| | |  __/\__ \
\t \__\___|\___|_| |_|_| |_|\___/|_|\___/ \__, |_|\___||___/
\t                                        |___/
\t[WEB-SERVER] => PHP Local Server Application
\tCreated By Hardy Hastings                                        
\tThis application is responsible for managing local server for development and debugging purposes.  
\n\n
";

echo($intro_text);
sleep(5); 

// Set the directory you want to serve
$cur_dir = dirname(dirname(dirname(__FILE__))).DIRECTORY_SEPARATOR.""; 
 
// Change to the specified directory
chdir($cur_dir);

// Define the command to start the PHP built-in server

if (file_exists('C:\levidoc\php\php.exe')){
    $command = ' C:\levidoc\php\php.exe -S 127.0.0.1:3000'; 
}else{
    $command = 'php -S 127.0.0.1:3000';
}
// Open a log file to capture the output
$hash = hash("sha256",date('d m Y')); 
#$filename = $cur_dir."/records/session.log.".$hash.".report.pxy"; 
#$logFile = fopen($filename, "w");

// Start the server process and redirect output to the log file
$process = popen($command, 'r');

if (is_resource($process)) {
}
?>