<?php 
// lock.site

#   TITLE   : Website Lock Script   
#   DESC    : Configure the website lock, this will be the used to lock the website.   
#   PROPRIETOR: VARSITYMARKET_TECHNOLOGIES
#   VERSION : 1.0.1.1
#   AUTHOR  : HARDY HASTINGS  
#   RELEASE : 2025/11/20

#Construcing The Website Lock; 
$target_file = dirname(dirname(dirname(__FILE__)))."/bin/lock.key";
$module_file = dirname(dirname(dirname(__FILE__)))."/bin\license.creator";
@include_once $module_file; 
$username = 'admin'; 
$password =  input("\tLock Password : "); 
$domain ='127.0.0.1'; 
$ip = '127.0.0.1';
$module = new license_creator($username,$password,$domain,$ip); 
$module->export($target_file); 
#Website Has Enabled Lock Authentication
echo "\n\tWebsite Lock Enabled\n";

?>