<?php 
#   TITLE   : Restart Website Engine Database   
#   DESC    : Once Database has been Destroyed or deleted, this script helps with creating a restored database structure with empty data. This does not delete existing databases. 
#   PROPRIETOR: VARSITYMARKET_TECHNOLOGIES
#   VERSION : 1.0.1.1
#   AUTHOR  : HARDY HASTINGS  
#   RELEASE : 2025/10/23

@include_once dirname(dirname(__FILE__)).DIRECTORY_SEPARATOR."module.database.php"; 

$database = dirname(dirname(dirname(__FILE__))).DIRECTORY_SEPARATOR."database".DIRECTORY_SEPARATOR."__ENGINE_DATABASE__.DB"; 

$wb_builder = new database_manager();
$wb_builder->override_connection($database);

$wb_builder->createTable("tbltheme", [
    'id' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
    "interface" => "TEXT NOT NULL", 
    "style"=>"TEXT NOT NULL",
    "script"=>"TEXT NOT NULL",
    "title" => "TEXT NOT NULL",
    "description"=> "TEXT NOT NULL",
    "tags" => "TEXT NOT NULL",
    "modules" => "TEXT NOT NULL",
    "distrubutor" => "TEXT NOT NULL", 
]); 

$wb_builder->createTable("tbltemplates", [
    'id' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
    "title" => "TEXT NOT NULL", 
    "data" => "TEXT NOT NULL",
    "theme"=>"INTEGER"
]); 

#A Canvas Is A Blank Board. The Page Sits On The Empty Canvas, Layers and Structures For The Canvas, Then You will notice the individual elements. 
$wb_builder->createTable("tblboard", [
    'id' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
    "theme" => "TEXT NOT NULL",
    "style"=>"TEXT NOT NULL",
    "script"=>"TEXT NOT NULL",
]); 

$wb_builder->createTable('tblcanvas',[
    'id' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
    'board' => 'INTEGER',
    "title" => 'TEXT', 
    "url" => 'TEXT',
    "description" => 'TEXT',
    "seo" => 'TEXT',  
    "keywords" => 'TEXT', 
]);

$wb_builder->createTable('tblLayer', [
    'id' => "INTEGER PRIMARY KEY AUTOINCREMENT", 
    "layer_id"=> "TEXT NOT NULL",
    'layer_data' => "TEXT NOT NULL", 
    'canvas' => 'INTEGER'
]); 

# All Individual Elements In The Canvas 
$wb_builder->createTable('tblelements_cell', [
    'id' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
    'element_id' => 'TEXT NOT NULL',
    'element_data' => 'TEXT NOT NULL',
]); 

$wb_builder->createTable('tblelements_structure', [
    'id' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
    # Foreign Key To tblemenets_cell.element_id
    'element_skeleton' => 'TEXT NOT NULL',
    # Structure Of Element To Always Guide System To Refer
    'title' => 'TEXT NOT NULL',
]); 
echo "\n\t Database Restoration Task\n\t[COMPLETED RESTORATION]\n\n"; 
?>