<?php
// local.serever.script

#   TITLE   : LOCAL PHP WEB SERVER   
#   DESC    : The local server will be used to run the control panel. This will run on port 3000 (default). To prevent local ports crashing with development ports, the application ports will m be different. 
#   PROPRIETOR: VARSITYMARKET_TECHNOLOGIES
#   VERSION : 1.0.1.2
#   AUTHOR  : HARDY HASTINGS  
#   RELEASE : 2025/10/23

// Set the directory you want to serve
$cur_dir = dirname(dirname(dirname(__FILE__))).DIRECTORY_SEPARATOR.""; 
 
// Change to the specified directory
chdir($cur_dir);

// Define the command to start the PHP built-in server

$port_request = input("\t Website Port [9000]: ") ?? '9000';

if (empty($port_request)){
    $port_request = "9000"; 
}

if (file_exists('C:\levidoc\php\php.exe')){
    $command = ' C:\levidoc\php\php.exe -S 127.0.0.1:'.$port_request; 
}else{
    $command = 'php -S 127.0.0.1:'.$port_request;
}

// Open a log file to capture the output
$hash = hash("sha256",date('d m Y')); 
#$filename = $cur_dir."/records/session.log.".$hash.".report.pxy"; 
#$logFile = fopen($filename, "w");

// Start the server process and redirect output to the log file
$process = popen($command, 'r');

if (is_resource($process)) {
}
?>