<?php 
#   TITLE   : Restart System Logs Database   
#   DESC    : Once Database has been Destroyed or deleted, this script helps with creating a restored database structure with empty data. This does not delete existing databases. 
#   PROPRIETOR: VARSITYMARKET_TECHNOLOGIES
#   VERSION : 1.0.1.1
#   AUTHOR  : HARDY HASTINGS  
#   RELEASE : 2025/10/23

$intro_text = " 
##############################################

    -- Developer Console --
    -- Configure the varsitymarket ecosystem. With this command line tool 

##############################################
\t__     ___    ____  ____ ___ _______   __
\t\ \   / / \  |  _ \/ ___|_ _|_   _\ \ / /
\t \ \ / / _ \ | |_) \___ \| |  | |  \ V /
\t  \ V / ___ \|  _ < ___) | |  | |   | |
\t   \_/_/   \_\_| \_\____/___| |_|   |_|
\t
\t __  __    _    ____  _  _______ _____
\t|  \/  |  / \  |  _ \| |/ / ____|_   _|
\t| |\/| | / _ \ | |_) | ' /|  _|   | |
\t| |  | |/ ___ \|  _ <| . \| |___  | |
\t|_|  |_/_/   \_\_| \_\_|\_\_____| |_|
\t
\t _            _                 _             _
\t| |_ ___  ___| |__  _ __   ___ | | ___   __ _(_) ___  ___
\t| __/ _ \/ __| '_ \| '_ \ / _ \| |/ _ \ / _` | |/ _ \ / __|
\t| ||  __/ (__| | | | | | | (_) | | (_) | (_| | |  __/\__ \
\t \__\___|\___|_| |_|_| |_|\___/|_|\___/ \__, |_|\___||___/
\t                                        |___/
\t[RESTART-DATABASE] => Restarts The System Logs Database
\tCreated By Hardy Hastings                                        
\tRestarts The Application System Logs Database, This will help incase the database is accidentally deleted.  
\n\n
";

echo($intro_text);
sleep(5); 

define("__cmd__",true);

@include_once dirname(dirname(dirname(__FILE__))).DIRECTORY_SEPARATOR."config.php"; 
$database = __DATABASE_ENV__['root'].DIRECTORY_SEPARATOR.__DATABASE_ENV__['logs.database']; 
$db = __DATABASE_LOGS__; 
$db->override_connection($database); 

# Database startup for system logs database

# System Global username
$db->createTable('users',[
    'user_id' =>'INTEGER PRIMARY KEY AUTOINCREMENT',
    'first_name' =>'TEXT NOT NULL',
    'last_name' =>'TEXT NOT NULL',
    'email' =>'TEXT NOT NULL UNIQUE',
    'username' =>'TEXT UNIQUE',
    'password_hash' =>'TEXT NOT NULL',
    'is_active' =>'TEXT',
    'role' =>'TEXT',
    'created_at' =>'DATE DEFAULT CURRENT_DATE',
    'updated_at' =>'DATE DEFAULT CURRENT_DATE',
    'auth' => 'TEXT', 
    'img' => 'TEXT',     
]);

$db->createTable('file_ver',[
    'id' =>'INTEGER PRIMARY KEY AUTOINCREMENT',
    'file_path' =>'TEXT NOT NULL',
    'hash' =>'TEXT NOT NULL',
    'last_modify' =>'TEXT NOT NULL UNIQUE',
    'updated_at' =>'DATE DEFAULT CURRENT_DATE',
]);

echo "Database Restoration Task\n[COMPLETED RESTORATION]\n\n"; 
?>